### PR TITLE
fix: better error message for invalid Helm Chart path during init

### LINKED ISSUE #2838: Unclear error message during init using path to existing Helm chart Chart.yaml file
**What happened?**  

While trying to initialize a project with DevSpace, I ran into an error message that was unclear to me at first. I had a Helm chart already, so I selected that option during init and specified the path to it in the form of `<dir>/Chart.yaml`. The error message told me that it couldn't continue because file `Chart.yaml` was missing. It didn't take me long to realize what I'd done wrong (that a Helm chart should always be a directory, not a file), so I wasn't blocked for long.

But, even though I got myself unblocked, I thought it would be pretty straightforward to contribute a fix to improve the error message. So I'm logging this issue and opening a PR to resolve it.

The error I got was:

```
? Please enter the relative path to your local Helm chart (e.g. ./chart) foo/Chart.yaml

error Local path `foo/Chart.yaml` is not a Helm chart (Chart.yaml missing)
```

**What did you expect to happen instead?**  

Clear error message telling me the problem was that I didn't select a directory.

For example, I think a clearer error message would be:

```
error Local path `foo/Chart.yaml` is not a Helm chart (path is not a directory)
```

**How can we reproduce the bug?** (as minimally and precisely as possible) 

On a system with Helm installed, in a test directory, follow Helm's [instructions](https://helm.sh/docs/helm/helm_create/) to create a chart. Then, run `devspace init` from the test directory. Attempt to specify the path to the Helm chart by specifying the path to the `Chart.yaml` file within it.

```
~/helm-test > devspace init


     %########%      
     %###########%       ____                 _____                      
         %#########%    |  _ \   ___ __   __ / ___/  ____    ____   ____ ___ 
         %#########%    | | | | / _ \\ \ / / \___ \ |  _ \  / _  | / __// _ \
     %#############%    | |_| |(  __/ \ V /  ____) )| |_) )( (_| |( (__(  __/
     %#############%    |____/  \___|  \_/   \____/ |  __/  \__,_| \___\\___|
 %###############%                                  |_|
 %###########%


info Detecting programming language...

? Select the programming language of this project other

? How do you want to deploy this project? 

? Do you already have a Helm chart for this project? Yes

? Which Helm chart do you want to use? 

? Please enter the relative path to your local Helm chart (e.g. ./chart) foo/Chart.yaml

error Local path `foo/Chart.yaml` is not a Helm chart (Chart.yaml missing)

? Which Helm chart do you want to use? 

? Please enter the relative path to your local Helm chart (e.g. ./chart) .

error Local path `.` is not a Helm chart (Chart.yaml missing)

? Which Helm chart do you want to use? 

? Please enter the relative path to your local Helm chart (e.g. ./chart) foo

? Do you want to develop this project with DevSpace or just deploy it?  [Use arrows to move, type to filter]  [Use arrows to move, type to filter]
> I want to develop this project and my current working dir contains the source code
  I just want to deploy this project
```

My devspace.yaml:
n/a

**Local Environment:**  
- DevSpace Version: 6.3.12
- Operating System: linux
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
n/a

### PR DESCRIPTION
**Pull request by mattwelke**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?**
Resolves #2838. See that issue for details.

New error message displayed when following the repro steps documented in the issue:

```
~/helm-test > helm create foo
Creating foo
~/helm-test > ls
foo
~/helm-test > cd foo
~/helm-test/foo > l
charts/  Chart.yaml  templates/  values.yaml
~/helm-test/foo > cd ..
~/helm-test > alias devspace=/home/matt/code/github.com/mattwelke/devspace/devspace
~/helm-test > devspace init


     %########%      
     %###########%       ____                 _____                      
         %#########%    |  _ \   ___ __   __ / ___/  ____    ____   ____ ___ 
         %#########%    | | | | / _ \\ \ / / \___ \ |  _ \  / _  | / __// _ \
     %#############%    | |_| |(  __/ \ V /  ____) )| |_) )( (_| |( (__(  __/
     %#############%    |____/  \___|  \_/   \____/ |  __/  \__,_| \___\\___|
 %###############%                                  |_|
 %###########%


info Detecting programming language...

? Select the programming language of this project other

? How do you want to deploy this project? 

? Do you already have a Helm chart for this project? Yes

? Which Helm chart do you want to use? 

? Please enter the relative path to your local Helm chart (e.g. ./chart) foo/Chart.yaml

error Local path `foo/Chart.yaml` is not a Helm chart (path is not a directory)

? Which Helm chart do you want to use? 

? Please enter the relative path to your local Helm chart (e.g. ./chart) .

error Local path `.` is not a Helm chart (Chart.yaml missing)

? Which Helm chart do you want to use? 

? Please enter the relative path to your local Helm chart (e.g. ./chart) foo

? Do you want to develop this project with DevSpace or just deploy it?  [Use arrows to move, type to filter]  [Use arrows to move, type to filter]
> I want to develop this project and my current working dir contains the source code
  I just want to deploy this project
```

Note the "path is not a directory".

**Please provide a short message that should be published in the DevSpace release notes**
Fixed an issue where DevSpace's error message given a path to a file within a Chart directory instead of the Chart directory itself was unclear

**What else do we need to know?** 

I didn't see any tests that called the function I changed, so I did not update or add any tests. But I did build the binary using the instructions in CONTRIBUTING.md and manually tested it. I used the built binary to produce the new command output above.

I followed instructions in CONTRIBUTING.md to run unit tests and integration tests. Integration tests did not pass, but I'm creating this PR to see if it was just my local env that prevented them from passing.

### CODE REVIEW

**Comment by deniseschannon** [comment]
Fixes DSP-5

File: pkg/devspace/configure/deployment.go [hunk 1]
```diff
@@ -141,8 +141,18 @@ func (m *manager) AddHelmDeployment(deploymentName string) error {
 				localChartPathRel = localChartPath
 			}
 
-			stat, err := os.Stat(path.Join(localChartPathRel, "Chart.yaml"))
-			if err != nil || stat.IsDir() {
+			pathStat, err := os.Stat(localChartPath)
```
Comment (lizardruss) [inline pkg/devspace/configure/deployment.go:144]: Could we use `localChartPathRel` here?

File: pkg/devspace/configure/deployment.go [hunk 2]
```diff
@@ -141,8 +141,18 @@ func (m *manager) AddHelmDeployment(deploymentName string) error {
...
+				return err
+			}
+
+			if !pathStat.IsDir() {
+				m.log.WriteString(logrus.InfoLevel, "\n")
+				m.log.Errorf("Local path `%s` is not a Helm chart (path is not a directory)", localChartPathRel)
+				continue
+			}
+
+			if _, err := os.Stat(path.Join(localChartPathRel, "Chart.yaml")); errors.Is(err, os.ErrNotExist) {
```
Comment (lizardruss) [inline pkg/devspace/configure/deployment.go:155]: Would this hide other potential errors? Perhaps something like the following would prevent that:
```golang
if _, err := os.Stat(path.Join(localChartPathRel, "Chart.yaml")); err != nil {
  m.log.WriteString(logrus.InfoLevel, "\n")
  if errors.Is(err, os.ErrNotExist) {
    m.log.Errorf("Local path `%s` is not a Helm chart (Chart.yaml missing)", localChartPathRel)
    continue
  } else {
    m.log.Errorf("Encountered unexpected error checking local path `%s`: %s", localChartPathRel, err.Error())
    continue
  }
}
```

**Review by lizardruss — CHANGES_REQUESTED** [review]
Nice work!

Just a couple minor changes.

**Comment by lizardruss** [comment]
@mattwelke 

Can you take a look at the review feedback?

**Comment by mattwelke** [comment]
@lizardruss Sorry about that, missed this in my inbox. Thanks for reviewing. I'll take a look soon!

File: pkg/devspace/configure/deployment.go (hunk 1 above)
Comment (mattwelke) [reply pkg/devspace/configure/deployment.go:144]: Agreed. Changed.

File: pkg/devspace/configure/deployment.go (hunk 2 above)
Comment (mattwelke) [reply pkg/devspace/configure/deployment.go:155]: Makes sense. Definitely a good idea to include handling unknown errors too. Changed.

**Comment by mattwelke** [comment]
Made the changes. Ran my test again. It looks good still (it behaves the same way as before where the error message talks about it being a directory).

```
 > <devspace_bin> init
```

```
     %########%      
     %###########%       ____                 _____                      
         %#########%    |  _ \   ___ __   __ / ___/  ____    ____   ____ ___ 
         %#########%    | | | | / _ \\ \ / / \___ \ |  _ \  / _  | / __// _ \
     %#############%    | |_| |(  __/ \ V /  ____) )| |_) )( (_| |( (__(  __/
     %#############%    |____/  \___|  \_/   \____/ |  __/  \__,_| \___\\___|
 %###############%                                  |_|
 %###########%


info Detecting programming language...

? Select the programming language of this project other

? How do you want to deploy this project? 

? Do you already have a Helm chart for this project? Yes

? Which Helm chart do you want to use? 

? Please enter the relative path to your local Helm chart (e.g. ./chart) my-chart/Chart.yaml

error Local path `my-chart/Chart.yaml` is not a Helm chart (path is not a directory)

? Which Helm chart do you want to use?  [Use arrows to move, type to filter]
> Use a local Helm chart (e.g. ./helm/chart/)
  Use a Helm chart repository (e.g. app-chart stored in https://charts.company.tld)
  Use a .tar.gz archive from URL (e.g. https://artifacts.company.tld/chart.tar.gz)
  Use a chart from another git repository (e.g. you have an infra repo)
  Abort and return to more options
```

**Review by lizardruss — APPROVED** [review]

**Review by lizardruss — CHANGES_REQUESTED** [review]
@mattwelke

Apologies, but the linting and e2e tests failed, but the cause may be unrelated to your changes. I'm aiming to resolve those with this [PR](https://github.com/devspace-sh/devspace/pull/2854).

Once complete, can you rebase your branch against main so we can try again?

**Comment by lizardruss** [comment]
> @mattwelke
> 
> Apologies, but the linting and e2e tests failed, but the cause may be unrelated to your changes. I'm aiming to resolve those with this [PR](https://github.com/devspace-sh/devspace/pull/2854).
> 
> Once complete, can you rebase your branch against main so we can try again?

@mattwelke I think you can go ahead and rebase this branch. There are some test flakes that will need more investigation, but imo they should not hold up this PR.

**Review by lizardruss — APPROVED** [review]
LGTM!
